fail_fast: true
default_install_hook_types: [pre-push]
exclude:
  glob: '**/snapshots/**'

repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
        exclude:
          glob: CHANGELOG.md
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: 37bb98842b0d8c4ffebdb75301a13db0267cef89  # frozen: v1.47.2
    hooks:
      - id: typos

  - repo: https://github.com/executablebooks/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547  # frozen: 1.0.0
    hooks:
      - id: mdformat
        language: python  # ensures that Renovate can update additional_dependencies
        args: [--number, --compact-tables, --align-semantic-breaks-in-lists]
        additional_dependencies:
          - mdformat-frontmatter==2.1.2
          - mdformat-mkdocs==5.1.4
          - mdformat-simple-breaks==0.1.0

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 5030dca3047414c338091455ac41803200ec1f0f  # frozen: 0.37.3
    hooks:
      - id: check-metaschema
        files:
          glob: prek.schema.json
      - id: check-github-workflows
      - id: check-renovate
        additional_dependencies: ['json5']

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 1376e3d73ce106474179c8adfda11d1e50b7d4dc  # frozen: v1.1.6
    hooks:
      - id: tombi-format
        args: ["--offline"]
        files: \.toml$

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster

      - id: cargo-clippy
        name: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy --all-targets --all-features -- -D warnings
