# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json
#:tombi toml-version = "v1.1.0"

fail_fast = true
default_install_hook_types = ["pre-push"]
exclude = { glob = "**/snapshots/**" }

[update]
cooldown_days = 7
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", exclude = { glob = "CHANGELOG.md" } },
  { id = "mixed-line-ending" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "8a48f81b6c64dcfea44b3633223084c4be58ac5f"  # frozen: v1.49.0
hooks = [{ id = "typos" }]

[[repos]]
repo = "https://github.com/executablebooks/mdformat"
rev = "82912cdaea4fb830f751504486a7879c70526547"  # frozen: 1.0.0
hooks = [
  {
    id = "mdformat",
    language = "python",
    args = ["--number", "--compact-tables", "--align-semantic-breaks-in-lists"],
    additional_dependencies = [
      "mdformat-frontmatter==2.1.2",
      "mdformat-mkdocs==5.2.1",
      "mdformat-simple-breaks==0.1.0",
    ]
  }
]

[[repos]]
repo = "https://github.com/python-jsonschema/check-jsonschema"
rev = "12e63946db2c5cfcc9030fac21c3883ba88c6ed8"  # frozen: 0.38.0
hooks = [
  {
    id = "check-metaschema",
    files = { glob = ["prek.schema.json", "prek-hooks.schema.json"] },
  },
  { id = "check-github-workflows" },
  {
    id = "check-renovate",
    additional_dependencies = ["json5"],
  }
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "dd68bbd8cdd8891c942fb6f33a6e87a477b2c375"  # frozen: v1.4.1
hooks = [
  { id = "tombi-format", args = ["--offline"], files = '\.toml$' },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo fmt",
    entry = "cargo fmt --",
    language = "system",
    types = ["rust"],
    pass_filenames = false,
  },
  {
    id = "cargo-clippy",
    name = "cargo clippy",
    language = "system",
    types = ["rust"],
    pass_filenames = false,
    entry = "cargo clippy --all-targets --all-features -- -D warnings",
  }
]
