name: Bug report
description: Create a report to help us improve prek
body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug, including a minimal reproducible example.
        If we cannot reproduce the bug, it is unlikely that we will be able to help you.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Willing to submit a PR?
      description: |
        If you have time, we welcome pull requests.
      options:
        - label: Yes — I’m willing to open a PR to fix this.

  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture are you using? (see `uname -orsm`)
      placeholder: e.g., macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of prek are you using? (see `prek -V`)
      placeholder: e.g., prek 0.2.3 (7fe75a86d 2025-09-29)
    validations:
      required: true

  - type: textarea
    attributes:
      label: .pre-commit-config.yaml
      description: |
        Please attach or paste the contents of your `.pre-commit-config.yaml` file if relevant.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Log file
      description: |
        Please attach or paste the contents of the trace log file located at:
        - Linux/macOS: `~/.cache/prek/prek.log`
        - Windows: `%LOCALAPPDATA%\prek\prek.log`
        If the log file doesn't exist or is empty, please run your command with increased verbosity:
        ```bash
        prek -vvv [your command]
        ```
    validations:
      required: true
