# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "identify>=2.6.16",
# ]
# ///

from identify.identify import ALL_TAGS
from identify.interpreters import INTERPRETERS
from identify.extensions import EXTENSIONS, EXTENSIONS_NEED_BINARY_CHECK, NAMES


DIRECT_TAG_CONSTS = [
    ("TAG_FILE", ["file"]),
    ("TAG_DIRECTORY", ["directory"]),
    ("TAG_SYMLINK", ["symlink"]),
    ("TAG_SOCKET", ["socket"]),
    ("TAG_EXECUTABLE", ["executable"]),
    ("TAG_NON_EXECUTABLE", ["non-executable"]),
    ("TAG_TEXT", ["text"]),
    ("TAG_BINARY", ["binary"]),
    ("TAG_TEXT_OR_BINARY", ["text", "binary"]),
]


def gen():
    with open("src/tags.rs", "w", newline='\n') as f:
        f.write("// This file is auto-generated by gen.py. DO NOT EDIT MANUALLY.\n\n")
        f.write("use crate::TagSet;\n\n")
        tags = sorted(set(ALL_TAGS))
        tag_to_id = {tag: idx for idx, tag in enumerate(tags)}

        def tagset_expr(tag_set):
            ids = sorted(tag_to_id[tag] for tag in tag_set)
            ids_str = ", ".join(str(tag_id) for tag_id in ids)
            return f"TagSet::new(&[{ids_str}])"

        f.write("pub const ALL_TAGS: phf::Set<&str> = phf::phf_set! {\n")
        for tag in tags:
            f.write(f'    "{tag}",\n')
        f.write("};\n\n")

        f.write(f"pub const ALL_TAGS_BY_ID: [&str; {len(tags)}] = [\n")
        for tag in tags:
            f.write(f'    "{tag}",\n')
        f.write("];\n\n")

        for const_name, const_tags in DIRECT_TAG_CONSTS:
            f.write(f"pub const {const_name}: TagSet = {tagset_expr(const_tags)};\n")
        f.write("\n")

        f.write("pub const INTERPRETERS: phf::Map<&str, TagSet> = phf::phf_map! {\n")
        for interpreter in sorted(INTERPRETERS):
            tag_names = sorted(INTERPRETERS[interpreter])
            tag_names_str = ", ".join(f'"{tag}"' for tag in tag_names)
            f.write(f"    // [{tag_names_str}]\n")
            f.write(f'    "{interpreter}" => {tagset_expr(INTERPRETERS[interpreter])},\n')
        f.write("};\n\n")

        EXTENSIONS.update(EXTENSIONS_NEED_BINARY_CHECK)
        f.write("pub const EXTENSIONS: phf::Map<&str, TagSet> = phf::phf_map! {\n")
        for ext in sorted(EXTENSIONS):
            tag_names = sorted(EXTENSIONS[ext])
            tag_names_str = ", ".join(f'"{tag}"' for tag in tag_names)
            f.write(f"    // [{tag_names_str}]\n")
            f.write(f'    "{ext}" => {tagset_expr(EXTENSIONS[ext])},\n')
        f.write("};\n\n")

        f.write("pub const NAMES: phf::Map<&str, TagSet> = phf::phf_map! {\n")
        for name in sorted(NAMES):
            tag_names = sorted(NAMES[name])
            tag_names_str = ", ".join(f'"{tag}"' for tag in tag_names)
            f.write(f"    // [{tag_names_str}]\n")
            f.write(f'    "{name}" => {tagset_expr(NAMES[name])},\n')
        f.write("};\n")

def main():
    gen()


if __name__ == "__main__":
    main()
