[profile.ci-core]
status-level = "skip"
final-status-level = "slow"
failure-output = "immediate"
fail-fast = false
test-threads = 8

[profile.ci-language]
inherits = "ci-core"
default-filter = "binary_id(prek::languages)"

[[profile.ci-language.overrides]]
# LuaRocks can hit a race condition when multiple processes are installing the same package.
filter = "test(lua::)"
threads-required = "num-cpus"
