name: "Publish to npmjs registry"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

env:
  UV_VERSION: "0.11.6"

jobs:
  publish:
    name: Upload to npmjs registry
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      # For npm's trusted publishing.
      id-token: write
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Fetch binary archives
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          pattern: artifacts-*
          path: npm-artifacts/
          merge-multiple: true
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - name: "Install uv"
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version: ${{ env.UV_VERSION }}
      - name: Build npm packages
        run: |
          printf '%s' "$PLAN" > plan-dist-manifest.json
          uv run ./scripts/build-npm-packages.py --plan plan-dist-manifest.json --artifacts-dir ./npm-artifacts --out-dir ./npm/.output
      - name: Publish npm packages
        run: |
          prerelease=$(echo "$PLAN" | jq --raw-output '.announcement_is_prerelease')
          jq --raw-output '.publishOrder[]' ./npm/.output/manifest.json | while IFS= read -r pkg; do
            if [ "$prerelease" = "true" ]; then
              npm publish --tag beta --provenance --access public "$pkg"
            else
              npm publish --provenance --access public "$pkg"
            fi
          done
